-- MySQL Script generated by MySQL Workbench
-- ke  3. maaliskuuta 2021 18.19.33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_store_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_store_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_store_database` ;
USE `online_store_database` ;

-- -----------------------------------------------------
-- Table `online_store_database`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_database`.`Users` ;

CREATE TABLE IF NOT EXISTS `online_store_database`.`Users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `firstname` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(30) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `idUsers_UNIQUE` (`userID` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store_database`.`ProductType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_database`.`ProductType` ;

CREATE TABLE IF NOT EXISTS `online_store_database`.`ProductType` (
  `idProductType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idProductType`),
  UNIQUE INDEX `idProductSection_UNIQUE` (`idProductType` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store_database`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_database`.`Products` ;

CREATE TABLE IF NOT EXISTS `online_store_database`.`Products` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `imageURL` VARCHAR(45) NOT NULL,
  `storage_amount` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `ProductType_idProductType` INT NOT NULL,
  PRIMARY KEY (`productID`),
  UNIQUE INDEX `productID_UNIQUE` (`productID` ASC) VISIBLE,
  INDEX `fk_Products_ProductType1_idx` (`ProductType_idProductType` ASC) VISIBLE,
  CONSTRAINT `fk_Products_ProductType1`
    FOREIGN KEY (`ProductType_idProductType`)
    REFERENCES `online_store_database`.`ProductType` (`idProductType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store_database`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_database`.`Payment` ;

CREATE TABLE IF NOT EXISTS `online_store_database`.`Payment` (
  `paymentID` INT NOT NULL AUTO_INCREMENT,
  `Users_userID` INT NOT NULL,
  `Products_productID` INT NOT NULL,
  `payment_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `package_posted` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_Users_has_Products_Products1_idx` (`Products_productID` ASC) VISIBLE,
  INDEX `fk_Users_has_Products_Users_idx` (`Users_userID` ASC) VISIBLE,
  PRIMARY KEY (`paymentID`),
  UNIQUE INDEX `paymentID_UNIQUE` (`paymentID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Products_Users`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `online_store_database`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Products_Products1`
    FOREIGN KEY (`Products_productID`)
    REFERENCES `online_store_database`.`Products` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
