-- MySQL Script generated by MySQL Workbench
-- Tue Mar 23 17:53:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_store_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_store_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_store_database` ;
USE `online_store_database` ;

-- -----------------------------------------------------
-- Table `online_store_database`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_database`.`User` ;

CREATE TABLE IF NOT EXISTS `online_store_database`.`User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `hash` VARCHAR(150) NOT NULL,
  `salt` VARCHAR(150) NOT NULL,
  `firstname` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(30) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUsers_UNIQUE` ON `online_store_database`.`User` (`userId` ASC) VISIBLE;

CREATE UNIQUE INDEX `username_UNIQUE` ON `online_store_database`.`User` (`username` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `online_store_database`.`User` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `online_store_database`.`ProductType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_database`.`ProductType` ;

CREATE TABLE IF NOT EXISTS `online_store_database`.`ProductType` (
  `product_typeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`product_typeId`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProductSection_UNIQUE` ON `online_store_database`.`ProductType` (`product_typeId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `online_store_database`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_database`.`Product` ;

CREATE TABLE IF NOT EXISTS `online_store_database`.`Product` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `imageURL` VARCHAR(45) NOT NULL,
  `storage_amount` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `product_typeId` INT NOT NULL,
  PRIMARY KEY (`productId`),
  CONSTRAINT `fk_Product_ProductType1`
    FOREIGN KEY (`product_typeId`)
    REFERENCES `online_store_database`.`ProductType` (`product_typeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `productID_UNIQUE` ON `online_store_database`.`Product` (`productId` ASC) VISIBLE;

CREATE INDEX `fk_Product_ProductType1_idx` ON `online_store_database`.`Product` (`product_typeId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `online_store_database`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_database`.`Payment` ;

CREATE TABLE IF NOT EXISTS `online_store_database`.`Payment` (
  `paymentId` INT NOT NULL AUTO_INCREMENT,
  `payment_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `package_posted` TINYINT(1) NOT NULL DEFAULT 0,
  `productId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`paymentId`),
  CONSTRAINT `fk_Payment_Product1`
    FOREIGN KEY (`productId`)
    REFERENCES `online_store_database`.`Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `online_store_database`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `paymentID_UNIQUE` ON `online_store_database`.`Payment` (`paymentId` ASC) VISIBLE;

CREATE INDEX `fk_Payment_Product1_idx` ON `online_store_database`.`Payment` (`productId` ASC) VISIBLE;

CREATE INDEX `fk_Payment_User1_idx` ON `online_store_database`.`Payment` (`userId` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
